# Development configuration with hot reload
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/package.json:/app/package.json:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
    command: ["npm", "run", "dev:watch"]
    ports:
      - "9229:9229"  # Debug port

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "24678:24678"  # Nuxt dev server port

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./bot:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
